# Generated by Django 4.2.6 on 2023-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='emali',
            field=models.EmailField(max_length=500, verbose_name='ادرس الکترونیکی'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=500, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='تلفن'),
        ),
    ]
