# Generated by Django 4.2.6 on 2024-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='null', max_length=225),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='null', upload_to='photo/profile/%Y/%m/%d/'),
        ),
    ]
