# Generated by Django 4.2.6 on 2023-11-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_tegs_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tegs',
            new_name='tags',
        ),
    ]
